---
- hosts: all
  gather_facts: true
  tasks:
  - name: Debug
    debug:
       msg: "The current date is {{ ansible_date_time.date }}, Operating system name is : {{ ansible_distribution }} on {{inventory_hostname}} machine (IP : {{ansible_default_ipv4.address}} )"
  - name: Get current user
    become: false
    local_action: command whoami
    register: username_on_the_host
  - name: Register password update
    lineinfile:
      path: password.txt
      line: "Password Update : {{ ansible_date_time.date }} {{ ansible_date_time.time}} {{username_on_the_host.stdout}}"
  - name: Read file
    debug: 
      msg: "{{lookup('file', '/home/masteransible/password.txt') }}"
