---
- hosts: all
  gather_facts: true
  tasks:
  - name: update password for tsserver user
    become: yes
    user:
        name: tsante
        update_password: always
        password: $6$mysecretsalt$ZB9R8AirQYAXhtfhOo2qdJz52FyNI6v3L6Uc3KNRP.arBKIYpcuEyQewT5qBAHoyQFwHkW6Z551Ql.cZ53GeY0
